In [ ]:
1. What is a Python library? Why do we use Python libraries?

In [ ]:
Python library = 
        py library is the collection of modules and functions.
        These libraries can be easily imported into Python scripts or programs, allowing developers 
        to leverage existing functionality without having to write the code from scratch. 
        Python libraries are designed to be reusable, modular, and extensible, making it easier for developers
        to build complex applications by assembling various components.
    
why to use ? = because it has optimize function means it can be use by plenty of user at a time.
               Code Reusability: Libraries encapsulate reusable code, saving developers time
               and effort by providing pre-built solutions for common tasks.

               Modularity: Libraries are often organized into modules, allowing developers to use only
               the specific functionality they need without having to import the entire library.

                Efficiency: Using established and optimized libraries can result in more efficient code, 
                as they are typically well-tested, debugged, and performance-tuned.

                Community Contribution: Python has a large and active community of developers who contribute to the creation and maintenance of numerous libraries.
                This collaborative effort results in a rich ecosystem of tools and resources.

                Focus on Higher-Level Logic: Libraries handle lower-level details, enabling developers
                to focus on the higher-level logic and specific requirements of their applications.
                
                Python libraries are essential for efficient and effective software development, 
                 providing a foundation of pre-built functionality that accelerates the creation of diverse applications.

In [ ]:
2. What is the difference between Numpy array and List?

In [ ]:
1)Homogeneity:
    List: Lists can contain elements of different data types. Each element in a list can be of a different type.
    
    NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. 
    This homogeneity allows for more efficient storage and operations.

2)Performance:
    List: Lists are more flexible but can be slower for numerical operations, especially when dealing with large datasets,
    due to Python's dynamic typing and the overhead of storing references to objects.
    
    NumPy Array: NumPy arrays are more efficient for numerical operations. They are implemented in C and allow for vectorized operations,
    which can significantly improve performance for numerical computations.

3)Memory Efficiency:
    List: Lists generally consume more memory because they store not only the data but also additional information 
    such as the type and reference count for each object.
    
    NumPy Array: NumPy arrays are more memory-efficient as they store elements of a single data type and 
    don't need to store type information for each element.

4)Functionality:
    List: Lists provide a general-purpose collection with a variety of methods and operations. 
    However, for mathematical and numerical operations, you might need to use explicit loops.
    
    NumPy Array: NumPy arrays provide a wide range of mathematical functions and operations
    (e.g., element-wise operations, linear algebra operations) that are optimized for efficiency.
    
5)Syntax:
    List: Lists have a straightforward syntax and are part of the core Python language.
    
    NumPy Array: NumPy provides a specific numpy.array class for creating arrays. 
    The syntax for array operations is often more concise and expressive.

In [ ]:
3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
import numpy as np
arr1 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr1.shape

(3, 4)

In [6]:
arr1.size

12

In [7]:
arr1.ndim

2

In [ ]:
4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [8]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
import numpy as np 
arr1
first_row = arr1[0] ## Access the first row

print("first row of the array",first_row) ##print the result


first row of the array [1 2 3 4]


In [ ]:
5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [10]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr1[2,3]

12

In [ ]:
6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [12]:
import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extracting odd-indexed elements
odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)



Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
7. How can you generate a ranodm 3x3 matrix with values between 0 and 1?

In [13]:
import numpy as np
np.random.randint(0,2,(3,3))

array([[1, 1, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [ ]:
8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
np.random.rand:
Generates random values from a uniform distribution in the half-open interval [0.0, 1.0).
Takes shape parameters as separate arguments.
The values generated are between 0 (inclusive) and 1 (exclusive).
                                                                               
np.random.randn:
Generates random values from a standard normal (Gaussian) distribution with a mean of 0 and a standard deviation of 1.
Takes shape parameters as separate arguments.
The generated values can be positive or negative, and they follow a bell-shaped curve around the mean (0). 
                                                                        
In short, np.random.rand generates values from a uniform distribution in a specific range, 
while np.random.randn generates values from a standard normal distribution with mean 0 and standard deviation 1.
The choice between them depends on the distribution you need for your particular use case.


In [ ]:
9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [14]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr.ndim

2

In [16]:
import numpy as np
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [17]:
arr1.ndim ##we increase the dimension of array by expand function.

3

In [ ]:
10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [18]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
import numpy as np
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
11. Consider the following matrix:

Matrix A : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python
   1)Index wise multiplication
    2)Matrix multiplication
    3)Add both the matrix
    4)Subtract matrix B from A
    5)Divide Matrix B by A.

In [20]:
import numpy as np

In [21]:
A = np.array([[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]])
A
    

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
B = np.array([[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]])
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
A*B ##index wise miltiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [24]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
B.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [27]:
A @ B.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [28]:
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [29]:
B - A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
B / A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
12.  Which function in Numpy can be used to swap the byte order of an array

In [ ]:
"byteswap" function is uesd in numpy to swap the byte of order of an array.

In [ ]:
13.  What is the significance of the np.linalg.inv function?

In [ ]:
The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. In other words, 
if you have a square matrix A, the result of np.linalg.inv(A) is a matrix B such that A.dot(B) = B.dot(A) = np.eye(A.shape[0]),
where np.eye is the identity matrix.

Here are some key points about the significance of np.linalg.inv:

Solving Linear Systems:
    One of the primary applications is solving systems of linear equations. If you have a system of equations represented
    as Ax = b, where A is a square matrix of coefficients, x is the vector of variables, and b is the vector of constants, 
    you can solve for x by taking the inverse of matrix A: x = np.linalg.inv(A).dot(b).

Matrix Equations:
    It is used in solving matrix equations of the form AX = B where A, X, and B are matrices. If you know A and B,
    you can find X by using X = np.linalg.inv(A).dot(B).

Eigenvalue Problems: 
    It is also used in solving eigenvalue problems, as the inverse of a matrix is related to its eigenvalues and eigenvectors.

It's important to note that not all matrices have inverses. A matrix must be square and have a non-zero determinant for
its inverse to exist. If the matrix is singular (having a determinant of 0), the np.linalg.inv function will raise a LinAlgError.
Therefore, it's a good practice to check the determinant before attempting to compute the inverse.


In [ ]:
14. What does the np.reshape function do, and how is it used?

In [ ]:
The np.reshape function in NumPy is used to change the shape of an array without changing its data. 
It allows you to reorganize the elements of an array into a different shape while maintaining the same data.

The basic syntax for np.reshape is:
               numpy.reshape(array, newshape, order='C')
        
array: The array you want to reshape.
newshape: The new shape you want for the array. It can be a tuple specifying the new dimensions.
order: (Optional) It specifies the order in which the elements are read from the original array during reshaping. 
It can be 'C' (row-major, default) or 'F' (column-major).
Here's an example of how to use np.reshape :              


In [31]:
import numpy as np

    # Create a 1D arr
arr = np.array([1, 2, 3, 4, 5, 6])

  # Reshape the array to a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
15. What is broadcasting in Numpy?

In [ ]:
Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes 
and sizes, making it possible to operate on these arrays element-wise without the need for explicit looping.
Broadcasting is particularly useful when working with arrays of different shapes in a concise and efficient manner.

The fundamental concept behind broadcasting is extending smaller arrays so that they have compatible shapes
for arithmetic operations. NumPy automatically performs the necessary operations to make the shapes compatible,
effectively replicating or "broadcasting" the smaller array to match the shape of the larger one.

The rules of broadcasting in NumPy are as follows:

1)If the arrays have a different number of dimensions:
               If one of the arrays has fewer dimensions, pad its shape on the left with ones until the dimensions match.
The sizes of the dimensions are compared element-wise, starting from the right. The dimensions are compatible if they are 
equal or one of them is 1. If neither condition is met, a ValueError is raised.

2)If the arrays have the same number of dimensions:
            The sizes of the dimensions are compared element-wise, starting from the right. The dimensions are compatible
if they are equal or one of them is 1. If neither condition is met, a ValueError is raised.

Broadcasting allows you to write concise and readable code while performing operations on arrays with different shapes.

Here's a simple example to illustrate broadcasting:

In [32]:
import numpy as np

# A 2x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# A 1x3 array
arr2 = np.array([10, 20, 30])

# Broadcasting the 1x3 array to the shape of the 2x3 array
result = arr1 + arr2

print(result)

[[11 22 33]
 [14 25 36]]
